name: ai_assistant
channels: 
    - defaults
    - conda-forge
dependencies:
    - python==3.7
    - pip=20.1.1
    - PyAudio
    - pip:
        - pyttsx3
        - SpeechRecognition
        - chatterbot
        - chatterbot_corpus
        - wikipedia
        - spacy
        - Flask-Cors
        